### ISSUE TITLE
[Feature] Add schedule to sections

### ISSUE THREAD

**Issue by NicKravchenko** [SoftwyRD/unimate-api#50]
# Description
The University API already allows the creation of users, selections, and sections for subjects. However, these sections must now have their schedules indicating when they will be offered.

## Problem
Sections doesn't have schedule 

## Solution
Create all corresponding logic to schedule and implement it into API

**Comment by OmarNunezG** [comment]
Working on it!

**Comment by OmarNunezG** [comment]
Done with ec8b0d5
